### PR TITLE
[2.x] Update dependencies.

### PR DESCRIPTION
**Pull request by XhmikosR**
**DO NOT MERGE**

I will update it when we have a new asset-resolver version :)

Would be nice if we could drop more dependencies in this branch too. If you are going to do this @bezoerb please ping me before cutting a new 2.x release; we need to test once with Node.js 6.0.0 to make sure we don't break something.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Actually, do not merge this, I need to update this after the asset-resolver 1.x fix is published.

**Comment by XhmikosR** [comment]
@bezoerb this is ready

**Comment by XhmikosR** [comment]
@bezoerb don't forget to release a new patch version :) BTW I tested this with Node.js 6.0.0 and it passed.

**Comment by bezoerb** [comment]
:) Thanks

**Pull request merged**
