### PR TITLE
Perf: Parallelise requests

### PR DESCRIPTION
**Pull request by Juice10**
I was processing some particularly large css files which where taking me about 6 minutes to inline.
After parallelising the requests I was able to bring this down to about 50 seconds.

### CODE REVIEW

**Review by bezoerb — APPROVED** [review]
LGtM

**Comment by bezoerb** [comment]
Awesome😊
Thanks @Juice10 🚀

**Comment by bezoerb** [comment]
[v7.0.1](https://github.com/bezoerb/postcss-image-inliner/releases/tag/v7.0.1)

**Comment by Juice10** [comment]
My pleasure @bezoerb! Thanks for the quick release!

**Pull request merged**
